rules = {
    1:  ("xmldokument", ["xmldecl", "element"]),
    2:  ("xmldokument", ["element"]),
    3:  ("xmldecl",     ["<?xml", "version=", "vernumb", "?>"]),
    4:  ("vernumb",     ["number", ".", "number"]),
    5:  ("element",     ["<", "name", "element′"]),
    6:  ("element′",    ["/>"]),
    7:  ("element′",    [">", "element′′"]),
    8:  ("element′′",   ["word", "endtag"]),
    9:  ("element′′",   ["elements", "endtag"]),
    10: ("element′′",   ["endtag"]),
    11: ("elements",    ["element"]),
    12: ("endtag",      ["</", "name", ">"]),
    13: ("name",        ["namestart", "nameend"]),
    14: ("namestart",   ["letter"]),
    15: ("namestart",   ["_"]),
    16: ("namestart",   [":"]),
    17: ("nameend",     ["namechar", "nameend"]),
    18: ("nameend",     []),
    19: ("namechar",    ["letter"]),
    20: ("namechar",    ["digit"]),
    21: ("namechar",    ["."]),
    22: ("namechar",    ["-"]),
    23: ("namechar",    ["_"]),
    24: ("namechar",    [":"]),
    25: ("letter",      ["LETTER"]),
    26: ("number",      ["digit", "number′"]),
    27: ("number′",     ["number"]),
    28: ("number′",     []),
    29: ("digit",       ["NUMBER"]),
    30: ("word",        ["char", "word′"]),
    31: ("word′",       ["word"]),
    32: ("word′",       []),
    33: ("char",        ["letter"]),
    34: ("char",        ["digit"]),
    35: ("char",        ["."]),
    36: ("char",        ["-"]),
    37: ("char",        ["_"]),
    38: ("char",        [":"]),
    39: ("char",        ["!"]),
    40: ("char",        ["@"]),
    41: ("char",        ["#"]),
}